name: j21ulian-alfaview # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: unofficial snap wrapper for Alfaview # 79 char long summary
description: |
  unofficial snap wrapper for Alfaview

contact: unquiet_clash_0c@icloud.com

grade: devel # must be 'stable' to release into candidate/stable channels
#confinement: devmode # use 'strict' once you have the right plugs and slots
confinement: devmode
architectures: 
  - amd64


# Some other things
compression: xz # Sets the compression type for the snap. 


parts:
#  my-part:
#    # See 'snapcraft plugins'
#    plugin: nil
  part-alfaview:
    plugin: dump
    source: .
    organize:
      alfaview: bin/
  remote-part:
    source: https://assets.alfaview.com/stable/linux/alfaview_8.46.1.deb
    source-type: deb
    plugin: dump
layout:
  /bin/alfaview:
    bind: $SNAP_DATA/opt/alfaview
